version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kata_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do
        echo 'Waiting for database...';
        sleep 2;
      done;
      npx prisma migrate dev --name init &&
      npm run start:dev
      "
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/kata_db
    depends_on:
      - db

volumes:
  db_data:
